config/routes.rb
Getadilla::Application.routes.draw do

  root to: "welcome#index"
  get '/signup' => "customers#new"
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/signout' => 'session#destroy'

  get '/orderdilla' => 'dillas#new'
  get '/orderhistory' => 'customers#show'
  get '/orderconfirmation' => 'customers#confirmation'

  resources :dillas
  resources :customers
  resources :ingredients

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  username        :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Customer < ActiveRecord::Base
  attr_accessible :name, :email, :username, :password, :password_confirmation

  has_secure_password

  has_many :dillas

  validates :name, :username, :email, :password, :password_confirmation, :presence => true
  validates :email, :uniqueness => true
  validates :password, :password_confirmation, :length => { in: 3..20 }

end

app/models/dilla.rb
# == Schema Information
#
# Table name: dillas
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  customer_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Dilla < ActiveRecord::Base
  attr_accessible :name, :customer_id
  belongs_to :customer
  has_and_belongs_to_many :ingredients
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :dillas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #before any action runs, run get user
  before_filter :get_user
  private
  def get_user
    #goal is to find the user currently logged in. a session is a hash with session id, csrf, and customer_id (added in the create method). if there is a customer_id (ie someone logged in), find that customer by the customer id, then assign it @customer instance variable.
    if session["customer_id"]
      @customer = Customer.find(session["customer_id"])
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def new
    # render customers/new signup form
    @customer = Customer.new
  end
  # POST /customers
  def create
    @customer = Customer.new(params[:customer])
    if @customer.save
      redirect_to(login_path)
      flash[:notice] = "You have successfully created an account. Please log in to get a face full of dillas!"
    else
      # go to customers/new.html.erb and just display that page.
      # in this action
      render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    if @customer.update_attributes(params[:customer])
      redirect_to(@customer)
    else
      render "edit"
    end
  end


#TODO what is this authenticate thing
  def authenticate
  end

  def dillas
    @customer.dillas
  end


end

app/controllers/dillas_controller.rb
class DillasController < ApplicationController
  def index
    @dillas = Dilla.where({customer_id: @customer.id}).all

  end

  def new
    @dilla = Dilla.new
  end

  def create
    dilla = Dilla.create(params[:dilla])
    @customer.dillas << dilla
    #Dilla.create(params[:dilla])
    redirect_to('/orderconfirmation')
    #TODO redirect to order confirmation page, which has links to order history and order more dillas
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    ingredient = params[:ingredient]
    Ingredient.create(ingredient)
    #Ingredient.create(params[:ingredient])
    #OPTIMIZE use named routes
    redirect_to(ingredients_path)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    @customer = Customer.where(email: email).first
    if @customer && @customer.authenticate(password)
      session[:customer_id] = @customer.id
      # redirect_to("/customers/#{customer.id}")
      redirect_to(@customer)
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:customer_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def sign_in(customer)
    cookies.permanent[:remember_token] = user.remember_token
    current_customer = customer
  end

  def signed_in?
    !current_customer.nil?
  end

  def current_customer=(customer)
    @current_customer = customer
  end

  def current_customer
    @current_customer ||= Customer.find_by_remember_token(cookies[:remember_token])
  end

  def current_customer?(customer)
    customer == current_customer
  end

  def sign_out
    current_customer = nil
    cookies.delete(:remember_token)
  end


  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
end

app/views/customers/_customer.html.erb
<% customer.password_digest %>
<% customer.email %>

app/views/customers/confirmation.html.erb
<title>YOU JUST GOT SOME DILLAS!!!!!!!!</title>

<p>We've received your order!!!!</p>

<div><%= link_to('Get More Dillas!', orderdilla_path) %></div>
<div><%= link_to('View Order History', dillas_path) %></div>

app/views/customers/edit.html.erb
<%= form_for(@customer) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Update Account" %>
<% end %>

app/views/customers/index.html.erb
<title>Customers</title>
<% @customers.each do |customer| %>
  <%= render partial: "customer", :locals => {:customer => customer} %>
<% end %>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
<ul>
  <% @customer.errors.messages.each do |error, msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(@customer) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/customers/show.html.erb
<h1> Hola, <%= @customer.name.capitalize %>!!!!!! </h1>
<%= render partial: 'customer', locals: {:customer => @customer } %>

<div><strong><%= link_to('Get a Dilla!', orderdilla_path) %></strong></div>

<div><%= link_to('View Order History', dillas_path) %></div>

app/views/dillas/index.html.erb
<h1>Order History</h1>

<% if @dillas.count < 3 %>
  <p> You've only ordered <%= @dillas.count %> dillas!?!?! HOW ARE YOU EVEN NAVIGATING THE INTERWEBS, LET'S GET YOU <%= link_to('SOME MORE DILLAS, STAT!', orderdilla_path)%> </p>
  <% elsif @dillas.count < 10 %>
  <p> You have a few dillas under your belt, but once you've ordered 10 dillas you'll be "the rilla dilla". <%= link_to('Did you forget one for your friend?', orderdilla_path)%> </p>
  <% else %>
  <p> You are an official killa of dillas. <%= link_to('KEEP AT IT, YOU DILLA PARTY MACHINE.', orderdilla_path)%></p>
<% end %>

<p> Here's a look at the dillas you've ordered in the past: </p>
<ul>
<% @dillas.each do |dilla| %>
<li>
 <div><%= dilla.name %></div>
 <div><%= dilla.created_at %></div>
</li>
<% end %>
</ul>

<br>

<div><%= link_to('Back to Order Page', orderdilla_path) %></div>

app/views/dillas/new.html.erb
<h1>Order Dillas</h1>

<%= form_for(@dilla) do |f| %>
  <select name="dilla[name]">
    <option value="Dilla from Manila">Dilla in Manila</option>
    <option value="Godzdilla">Godzdilla</option>
    <option value="Ghostface Dilla">Ghostface Dilla</option>
    <option value="All Dilla No Filla">All Dilla No Filla</option>
    <option value="The de Blasio, Billadilla">The de Blasio, Billadilla</option>
    <option value="Guerilladilla">Guerilladilla</option>
  </select>

  <%= f.submit "Get Dillas" %>
<% end %>


<div class="menu">
  <div class="menu_title">
    <h3><strong> OUR DILLAS: </strong></h3>
  </div>
  <div class="menu_item">
    <h4> Dilla in Manila </h4>
    <p> <em> Sriracha-loaded dillamonster that will knock your hunger out (that's not funny, but neither is this dilla...it's dead serious)! </em></p>
  </div>
  <div class="menu_item">
    <h4> Godzdilla </h4>
    <p> <em>A dilla of mythic proportions, known to cause citizens of global metropolises (sp?) to flee in fear </em></p>
  </div>
  <div class="menu_item">
    <h4> Ghostface Dilla </h4>
    <p> <em>The cheesiest, most delicious member of the Wu-Tang Clan </em></p>
  </div>
  <div class="menu_item">
    <h4> All Dilla No Filla </h4>
    <p> <em> The most glorious dilla of all time </em></p>
  </div>
  <div class="menu_item">
    <h4> The de Blasio, Billadilla  </h4>
    <p> <em> The unofficial dilla of the de Blasio campaign for mayor of the great city of Nueva York </em></p>
  </div>
  <div class="menu_item">
    <h4> Guerilladilla  </h4>
    <p> <em> Che loved him some dillas...this dilla goes great with your t-shirt! </em></p>
  </div>
</div>

app/views/dillas/show.html.erb
<h1>Customers</h1>
<% @customers.each do |customer| %>
  <%= render partial: "customer", :locals => {:customer => customer} %>
<% end %>

app/views/layouts/_footer.html.erb
  <footer>
    <% if session[:customer_id] %>
      <%= link_to "Sign out", signout_path, method: "delete" %>
      <%= link_to("Update Your Account Information", edit_customer_path(@customer)) %>
    <% end %>
  &#169;2013 GETADILLA
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getadilla</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="google-translate-customization" content="8ee2914ddfd0efbb-e8d2cedfbc155bf3-g2a4e8419b2c32bd3-e"></meta>

  <link href='http://fonts.googleapis.com/css?family=Frijole' rel='stylesheet' type='text/css'>

  <link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>


</head>
<body>
<% if flash[:notice] -%><div><%= flash[:notice] %></div><% end %>

  <div id="google_translate_element"></div><script type="text/javascript">
  function googleTranslateElementInit() {
    new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
  }
  </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<div id="container">
  <header>
    <div id="logo">
      GETADILLA
    </div>

  </header>

  <div id="wrapper">
    <%= yield %>
  </div>

<%= render partial: 'layouts/footer' %>
</div>
</body>
</html>

app/views/session/new.html.erb
<h1>Login</h1>

<em><% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %></em>

<%= form_tag('/login') do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Login" %>
<% end %>

app/views/welcome/index.html.erb
<h2>WELCOME TO GETADILLA, HOME OF THE WORLD'S BEST QUESADILLAS</h2>

<body>
  <div>
    <span class="links"><%= link_to('SIGN UP!', '/signup') %></span>
    <span class="links"><%= link_to('LOG IN!', '/login') %></span>
  </div>

  <div class="menu">
    <div class="menu_title">
      <h3><strong> OUR DILLAS: </strong></h3>
    </div>
    <div class="menu_item">
      <h4> Dilla in Manila </h4>
      <p> <em> Sriracha-loaded dillamonster that will knock your hunger out (that's not funny, but neither is this dilla...it's dead serious)! </em></p>
    </div>
    <div class="menu_item">
      <h4> Godzdilla </h4>
      <p> <em>A dilla of mythic proportions, known to cause citizens of global metropolises (sp?) to flee in fear </em></p>
    </div>
    <div class="menu_item">
      <h4> Ghostface Dilla </h4>
      <p> <em>The cheesiest, most delicious member of the Wu-Tang Clan </em></p>
    </div>
    <div class="menu_item">
      <h4> All Dilla No Filla </h4>
      <p> <em> The most glorious dilla of all time </em></p>
    </div>
    <div class="menu_item">
      <h4> The de Blasio, Billadilla  </h4>
      <p> <em> The unofficial dilla of the de Blasio campaign for mayor of the great city of Nueva York </em></p>
    </div>
    <div class="menu_item">
      <h4> Guerilladilla  </h4>
      <p> <em> Che loved him some dillas...this dilla goes great with your t-shirt! </em></p>
    </div>
  </div>
</body>